"""LLM capacity and cost planning for Claude deployments.

`catalog` holds the reference data (pricing, platform quotas); `planner`
turns a workload description into verdicts, costs and next actions.
"""

from cloudcost.llm.catalog import (
    MAX_OUTPUT_TOKENS,
    VERIFIED,
    Limit,
    LimitStatus,
    LLMModel,
    LLMPlatform,
    LineInfo,
    ModelInfo,
    ModelLine,
    ModelPricing,
    QuotaPlan,
    get_line,
    get_model,
    list_lines,
    list_models,
    list_plans,
    model_for,
)
from cloudcost.llm.planner import (
    Action,
    ActionKind,
    AppWorkload,
    CostEstimate,
    DimensionResult,
    LLMWorkload,
    ModelComparison,
    QuotaOverride,
    QuotaPlanResult,
    QuotaReport,
    Sensitivity,
    Verdict,
    compare_models,
    evaluate_workload,
    size_from_scenario,
)

__all__ = [
    "MAX_OUTPUT_TOKENS",
    "VERIFIED",
    "Action",
    "ActionKind",
    "AppWorkload",
    "CostEstimate",
    "DimensionResult",
    "LLMModel",
    "LLMPlatform",
    "LLMWorkload",
    "LineInfo",
    "ModelLine",
    "ModelComparison",
    "Limit",
    "LimitStatus",
    "ModelInfo",
    "ModelPricing",
    "QuotaOverride",
    "QuotaPlan",
    "QuotaPlanResult",
    "QuotaReport",
    "Sensitivity",
    "Verdict",
    "compare_models",
    "evaluate_workload",
    "get_line",
    "get_model",
    "list_lines",
    "list_models",
    "list_plans",
    "model_for",
    "size_from_scenario",
]
